version: '2'
services:
    zookeeper:
        image: wurstmeister/zookeeper:3.4.6
        ports:
            - 2181:2181
    kafka:
        image: wurstmeister/kafka:2.12-2.1.0
        environment:
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "topic-101"
        ports:
            - 9092:9092
